version: "3.3"

# name: "domo"

services:

##############################################################################
#                         DOMOTICA                                           #
##############################################################################

  homeassistant:
    container_name: ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${DOCKERSDIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus:/var/run/dbus:ro
    environment:
      - TZ=${TZ}
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2252437-if00:/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2252437-if00
    restart: always
    privileged: true
    network_mode: host

  # node-red:
  #   image: nodered/node-red
  #   container_name: node
  #   environment:
  #     - TZ=${TZ}
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - ${DOCKERSDIR}/nodered/data:/data
  #   restart: unless-stopped

  deconz:
    image: deconzcommunity/deconz:stable
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - ${DOCKERSDIR}/deconz:/opt/deCONZ
    devices:
        - /dev/ttyACM0
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DECONZ_WEB_PORT=480
      - DECONZ_WS_PORT=4443
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5902
      - DECONZ_VNC_PASSWORD=${CONTRASENA}
      # - DEBUG_INFO=1
      # - DEBUG_APS=0
      # - DEBUG_ZCL=0
      # - DEBUG_ZDP=0
      # - DEBUG_OTAU=0

  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mqtt
  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"
  #   command: "mosquitto -c /mosquitto-no-auth.conf"
  #   volumes:
  #    - ${DOCKERSDIR}/mqtt/config:/mosquitto/config
  #    - ${DOCKERSDIR}/mqtt/data:/mosquitto/data
  #    - ${LOGS}/mqtt:/mosquitto/log
  #   restart: unless-stopped
  #   networks:
  #     sistema_default:
  #         ipv4_address: ${APP_MQTT_IP}

  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   restart: unless-stopped
  #   image: koenkk/zigbee2mqtt
  #   volumes:
  #     - ${DOCKERSDIR}/zigbee2mqtt/data:/app/data
  #     - /run/udev:/run/udev:ro
  #   ports:
  #     - 8085:8080
  #   environment:
  #     - TZ=${TZ}
  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   depends_on:
  #     - mqtt
  #   networks:
  #       sistema_default:
  #           ipv4_address: ${APP_Z2M_IP}

# networks:
#   sistema_default:
#      external: true
