version: "3"
# name: nube
services:
  ########################################################################
  #                              NEXTCLOUD                               #
  ########################################################################

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${CONTRASENA}
    volumes:
      - /home/javier/docker/mariadb/:/config
      - /home/javier/docker/mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      reddocker:
        ipv4_address: ${APP_MARIADB_IP}
        
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nube
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERSDIR}/nube/appdata:/config
      - ${DATOSNUBE}:/data
    ports:
      - 2443:443
      - 280:80
    external_links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    restart: always
    networks:
      reddocker:
        ipv4_address: ${APP_NEXTCLOUD_IP}
        
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 9980:80
    environment:
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 15230247
      # MYSQL_ROOT_PASSWORD: 15230247
      - PMA_ARBITRARY=1 # display the field to enter the server to connect to
      - UPLOAD_LIMIT=300000000 # increased to 300 MB approx  
    links:
      - mariadb:mariadb
    networks:
      reddocker:
        ipv4_address: ${APP_PHPMYADMIN_IP}
        
networks:
  reddocker:
    external: true
